# Netlify Configuration
[build]
  publish = "dist"
  command = "npm run build"

# Force HTTPS
[[redirects]]
  from = "http://hihoney.site/*"
  to = "https://hihoney.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hihoney.site/*"
  to = "https://hihoney.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.hihoney.site/*"
  to = "https://hihoney.site/:splat"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and Performance Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Force HTTPS
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # Prevent clickjacking
    X-Frame-Options = "SAMEORIGIN"
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy
    Content-Security-Policy = "upgrade-insecure-requests"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

